name: Deploy Blog

on:
  push:
    branches:
      - main

# 允许 Actions 写入 GitHub Pages
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./          # 整个仓库根目录就是网站
          publish_branch: gh-pages
          exclude_assets: '.github,README.md'
